spring:
  application:
    name: kafka-producer
  kafka:

#    consumer:
#      group-id: simple-consumer-group
#      auto-offset-reset: earliest
      producer:
        spring.json.add.type.headers: false
        bootstrap-servers: localhost:9092
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        key-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
server:
  port: 8081